front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }

front_user_register:
    path:     /register
    defaults: { _controller: FrontBundle:User:register }

front_user_login:
    path:     /login
    defaults: { _controller: FrontBundle:User:login }

front_user_login_check:
    path:     /login_check

front_user_logout:
    path:     /logout

front_user_activate:
    path:     /activate/{token}
    defaults: { _controller: FrontBundle:User:activate }

front_user_forget_pass:
    path:     /forget
    defaults: { _controller: FrontBundle:User:forget }

front_user_reset:
    path:     /reset/{token}
    defaults: { _controller: FrontBundle:User:reset }

front_user_get_invitaitions:
    path:     /get/invitations
    defaults: { _controller: FrontBundle:User:getInvitations }

front_user_set_invitaition:
    path:     /set/invitation/attributes
    defaults: { _controller: FrontBundle:User:setInvitationAttributes }

front_user_set_invitaition_status:
    path:     /set/invitation/status
    defaults: { _controller: FrontBundle:User:setInvitationStatus }

front_list:
    prefix: /events
    resource: event_routing.yml
